# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

production:
  qiniu_access_key: krk1ZFFYgDtIo9nqwgDe027BP3IWY4lXYHizb-O3
  qiniu_secret_key: XEUY7dBVc4Ywm19DkljqADFNzGW6VhA9n4wGHTvm
  qiniu_bucket: lonelyreader
  qiniu_bucket_domain: oqjzv3tfi.bkt.clouddn.com
  SEND_CLOUD_USER_NAME: zhiduo_test_VkPm2e
  SEND_CLOUD_USER_KEY: GBlZH01f3e46C6Rb
  GOOGLE_CLIENT_ID: '359666636162-g1j0jj1cddqpmp3hr932n1lo4shav356.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: 'Xyk2VuwEauy_V3oeLqB9vOPq'

development:
  qiniu_access_key: krk1ZFFYgDtIo9nqwgDe027BP3IWY4lXYHizb-O3
  qiniu_secret_key: XEUY7dBVc4Ywm19DkljqADFNzGW6VhA9n4wGHTvm
  qiniu_bucket: lonelyreader
  qiniu_bucket_domain: oqjzv3tfi.bkt.clouddn.com
  SEND_CLOUD_USER_NAME: zhiduo_test_VkPm2e
  SEND_CLOUD_USER_KEY: GBlZH01f3e46C6Rb
  GOOGLE_CLIENT_ID: '359666636162-g1j0jj1cddqpmp3hr932n1lo4shav356.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: 'Xyk2VuwEauy_V3oeLqB9vOPq'
